### ISSUE TITLE
ARM builds?

### ISSUE THREAD

**Issue by konstantinblaesi** [coldfix/certbot-dns-netcup#13]
Is it possible to provide ARM builds out of the box ? I checked the base image https://hub.docker.com/r/certbot/certbot/tags?page=1&name=arm64 and simply built the Dockerfile using the base image tag 'arm64v8-v1.26.0'.
I have setup an ARM Ampere vps in the oracle free cloud tier and this is why I needed this architecture.

Assuming podman instead of docker is used on linux one just needs to

1. clone this repo
3. replace first line with 'FROM docker.io/certbot/certbot:arm64v8-v1.26.0'
4. change to the directory of the Dockerfile and run `podman build -t certbot-netcup .`

This results in a local image 'localhost/certbot-netcup' which works on the mentioned ARM machine.

(if using docker just replace 'podman' with 'docker')

**Comment by coldfix** [comment]
Hi,

I might have got this to work now, but you should better check whether it works (latest version 1.1.2). It's a bit suspicious that the image sizes are identical.

Best

**Comment by konstantinblaesi** [comment]
Hi,

I tried the image and it still crashed as it usually does when the architecture is wrong. Here are some steps I used to confirm that the image still contains amd64 instead of arm64 binaries

```
$ image=docker.io/coldfix/certbot-dns-netcup:latest
$ podman pull $image
Trying to pull docker.io/coldfix/certbot-dns-netcup:latest...
Getting image source signatures
Copying blob a860e27ad689 done  
Copying blob 339de151aab4 done  
Copying blob c6c8e9f0153d done  
Copying blob 910a9a405b4b done  
Copying blob d397e2192fef done  
Copying blob bde2ad12a253 done  
Copying blob 3fb10b303714 done  
Copying blob 75303e53b8f0 done  
Copying blob aaed35ce1e39 done  
Copying blob 382c4f12dd55 done  
Copying blob 42fcc09e2708 done  
Copying blob 4159d49c5283 done  
Copying blob 3bb01cd6d90b done  
Copying blob ca74f386f2a7 done  
Copying blob 2842b3cb4c03 done  
Copying config ebd927203c done  
Writing manifest to image destination
Storing signatures
ebd927203c04facc90dd10aaf6e04af83d8a3bbfa8169eeddba597f8bac194a5
$ podman image inspect $i | jq -r '.[] | .Architecture'
arm64
$ podman create --name temp $image
19c6eb4ce33212f2263478fb06262229a0d303fd6b892116fdc8dd550f16e38b
$ podman cp temp:/bin/busybox .
$ file busybox 
busybox: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

Using tag '1.1.2' instead of 'latest' does not change the result.

**Comment by coldfix** [comment]
Okay, thanks for checking!

Since Docker Hub seemed to have disabled automatic builds on free accounts, I had to change my image build process for this over to github actions, and had just hoped it worked by simply passing `arch64` as target platform to the build action. Apparently not. I already had my suspicions that it didn't really work considering the identical image sizes.

> `podman image inspect $image | jq -r '.[] | .Architecture'`

Thanks for that line. I'll try to get an image that produces the correct platform tag before calling back.

**Comment by coldfix** [comment]
Weirdly, my docker reports that the image is tagged as `arm64` (at least one of the two), but since the sizes are exactly equal, it just can't be right...

```shell
$ docker pull coldfix/certbot-dns-netcup
[...]

$ docker pull coldfix/certbot-dns-netcup --platform arm64
[...]

$ docker image list
REPOSITORY                          TAG        IMAGE ID       CREATED         SIZE
coldfix/certbot-dns-netcup          <none>     5ed502c7b119   23 hours ago    122MB
coldfix/certbot-dns-netcup          latest     ebd927203c04   23 hours ago    122MB
[...]

$ docker inspect ebd927203c04 | grep Architecture
        "Architecture": "arm64",

$ docker inspect 5ed502c7b119 | grep Architecture
        "Architecture": "amd64",

$ docker inspect 5ed502c7b119 | grep Size
        "Size": 122067609,
        "VirtualSize": 122067609,

$ docker inspect ebd927203c04 | grep Size
        "Size": 122067609,
        "VirtualSize": 122067609,
```

**Comment by coldfix** [comment]
Hi,

okay I hope it should work now.

so, my previous attempt was based on the assumption that certbot also had multi-arch images. I looked at the list of tags and clearly remember there were multiple architectures listed on the same tag. However, turns out I was probably looking at alpine or something else at the time. certbot provides arm64 builds only in separate tags as linked by you in your original post.

So I'll use separate tags as well for now. You should now be able to pull `arm64-latest` and get an actual arm64 image. I'll try to make a proper multi-arch image when I get it working.

Let me know if there are still problems.

**Comment by konstantinblaesi** [comment]
Hi,

amazing it works now, I checked both the tags `:latest` and `arm64-latest`, no `--platform` required (since I am on arm64 anyway).

Thanks for the support!

**Comment by coldfix** [comment]
Awesome!
