### ISSUE TITLE
QUESTION: Will the docker container check for updates if run continuously 

### ISSUE THREAD

**Issue by the-unknown** [coldfix/certbot-dns-netcup#33]
I am planing to run this via docker compose in combination with other containers.
I am wondering if I can run this continuously and if I do so if it will renew certificates automatically.

**Comment by coldfix** [comment]
Hey, in principle it can easily be run repeatedly in a container with a scheduling service such as crond. The current image may not contain this, as it is meant to be invoked as application. Personally, I'm using the host crond to regularly start the container, rather than keep a container running and schedule through its own crond. But the choice is a matter of taste and preferences.
